# from simsio import gen_configs
# import numpy as np
# params = {
#     "train_frac": np.arange(6, 10) / 10,
#     "augment_frac": np.arange(4) / 3,
# }
# gen_configs("template", params, "II/1B")
===:
  template: |
    n$enum:
      <<<: common
      input: {train_frac: $train_frac, augment_frac: $augment_frac}
  common:
    samples: 100
    input:
      N: 4000
      rescale: 50
      offset: 0
      augment_std: 0.05
    model:
      layers:
      - tf.keras.layers.Dense(2, activation="relu")
      - tf.keras.layers.Dense(20, activation="relu")
      - tf.keras.layers.Dense(20, activation="relu")
      - tf.keras.layers.Dropout(0.2)
      - tf.keras.layers.Dense(1, activation="sigmoid")
    compile:
      loss: binary_crossentropy
      optimizer: adam
      metrics: [accuracy]
      steps_per_execution: 4
    fit:
      epochs: 500
      batch_size: 50
      verbose: 0
61849a4ca72011ec9867fa163efacce8:
  <<<: common
  input: {train_frac: 0.6, augment_frac: 0.0}
61846126a72011ecb4f4fa163efacce8:
  <<<: common
  input: {train_frac: 0.6, augment_frac: 0.3333333333333333}
6137f2d2a72011ecabe9fa163e595e79:
  <<<: common
  input: {train_frac: 0.6, augment_frac: 0.6666666666666666}
62250a04a72011eca3effa163e04b9dc:
  <<<: common
  input: {train_frac: 0.6, augment_frac: 1.0}
6225036aa72011ec975afa163e04b9dc:
  <<<: common
  input: {train_frac: 0.7, augment_frac: 0.0}
6b0cb374a72011ec8ed7fa163e209104:
  <<<: common
  input: {train_frac: 0.7, augment_frac: 0.3333333333333333}
66e760a0a72011ecb5cbfa163ea6f025:
  <<<: common
  input: {train_frac: 0.7, augment_frac: 0.6666666666666666}
67e123b0a72011ec96e3fa163e209104:
  <<<: common
  input: {train_frac: 0.7, augment_frac: 1.0}
6d785028a72011eca5e3fa163ea6f025:
  <<<: common
  input: {train_frac: 0.8, augment_frac: 0.0}
66e5ff44a72011ec9536fa163ea6f025:
  <<<: common
  input: {train_frac: 0.8, augment_frac: 0.3333333333333333}
62245d66a72011ec8c7cfa163e66c7df:
  <<<: common
  input: {train_frac: 0.8, augment_frac: 0.6666666666666666}
622124f2a72011ecbf84fa163e209104:
  <<<: common
  input: {train_frac: 0.8, augment_frac: 1.0}
6137f8cca72011ec813bfa163e595e79:
  <<<: common
  input: {train_frac: 0.9, augment_frac: 0.0}
62245ed8a72011ec9e97fa163e66c7df:
  <<<: common
  input: {train_frac: 0.9, augment_frac: 0.3333333333333333}
61382c8ea72011ec86f9fa163e595e79:
  <<<: common
  input: {train_frac: 0.9, augment_frac: 0.6666666666666666}
6a4ecfbca72011ecbf34fa163efacce8:
  <<<: common
  input: {train_frac: 0.9, augment_frac: 1.0}


































