# from simsio import gen_configs
# params = {
#     "activation": [
#         "elu",
#         "relu",
#         "sigmoid",
#         "softsign",
#         "tanh",
#     ],
#     "optimizer": [
#         "adam",
#         "adamax",
#         "rmsprop",
#         "sgd",
#     ],
# }
# gen_configs("template", params, "II/2A")
===:
  template: |
    n$enum:
      <<<: common
      compile: {optimizer: $optimizer}
      model: {vars: {activation: $activation}}
  common:
    samples: 100
    input:
      N: 8000
      train_frac: 0.8
      rescale: 50
      offset: 0
    model:
      layers:
      - tf.keras.layers.Dense(2, activation=activation)
      - tf.keras.layers.Dense(20, activation=activation)
      - tf.keras.layers.Dense(20, activation=activation)
      - tf.keras.layers.Dropout(0.2)
      - tf.keras.layers.Dense(1, activation="sigmoid")
    compile:
      loss: binary_crossentropy
      metrics: [accuracy]
      steps_per_execution: 4
    fit:
      epochs: 500
      batch_size: 50
      verbose: 0
d1fe909ca68b11ecbdfcfa163ea6f025:
  <<<: common
  compile: {optimizer: adam}
  model: {vars: {activation: elu}}
1097a106a68011ecb0edfa163e209104:
  <<<: common
  compile: {optimizer: adamax}
  model: {vars: {activation: elu}}
b05e99aaa68b11ecbe72fa163ea6f025:
  <<<: common
  compile: {optimizer: rmsprop}
  model: {vars: {activation: elu}}
b4db32a4a68b11ecb056fa163ea6f025:
  <<<: common
  compile: {optimizer: sgd}
  model: {vars: {activation: elu}}
155d0ee2a68011eca3a3fa163e66c7df:
  <<<: common
  compile: {optimizer: adam}
  model: {vars: {activation: relu}}
154dbecea68011eca0d2fa163e66c7df:
  <<<: common
  compile: {optimizer: adamax}
  model: {vars: {activation: relu}}
b05dcffca68b11ecafddfa163ea6f025:
  <<<: common
  compile: {optimizer: rmsprop}
  model: {vars: {activation: relu}}
1a156d80a68011ec9a8afa163e66c7df:
  <<<: common
  compile: {optimizer: sgd}
  model: {vars: {activation: relu}}
10289feaa68011ecad35fa163e209104:
  <<<: common
  compile: {optimizer: adam}
  model: {vars: {activation: sigmoid}}
1542758ca68011ec9f62fa163e66c7df:
  <<<: common
  compile: {optimizer: adamax}
  model: {vars: {activation: sigmoid}}
10a52a38a68011ecb5dbfa163e209104:
  <<<: common
  compile: {optimizer: rmsprop}
  model: {vars: {activation: sigmoid}}
2f0b399aa68011ecbda5fa163e66c7df:
  <<<: common
  compile: {optimizer: sgd}
  model: {vars: {activation: sigmoid}}
1074bda8a68011ec97aefa163e209104:
  <<<: common
  compile: {optimizer: adam}
  model: {vars: {activation: softsign}}
104b25d8a68011ec836dfa163e209104:
  <<<: common
  compile: {optimizer: adamax}
  model: {vars: {activation: softsign}}
109f0de2a68011ec86a4fa163e209104:
  <<<: common
  compile: {optimizer: rmsprop}
  model: {vars: {activation: softsign}}
157b460aa68011ec8b34fa163e66c7df:
  <<<: common
  compile: {optimizer: sgd}
  model: {vars: {activation: softsign}}
15577298a68011ec8af6fa163e66c7df:
  <<<: common
  compile: {optimizer: adam}
  model: {vars: {activation: tanh}}
107a39f4a68011ec84e5fa163e209104:
  <<<: common
  compile: {optimizer: adamax}
  model: {vars: {activation: tanh}}
157fe066a68011ecb616fa163e66c7df:
  <<<: common
  compile: {optimizer: rmsprop}
  model: {vars: {activation: tanh}}
107ef7d2a68011ecb7fdfa163e209104:
  <<<: common
  compile: {optimizer: sgd}
  model: {vars: {activation: tanh}}










































