# from simsio import gen_configs
# import numpy as np
# params = {
#     "K": np.arange(1, 6),
#     "dropout": np.arange(4) / 10,
# }
# gen_configs("template", params, "II/2C")
===:
  template: |
    n$enum:
      <<<: common
      model: {<<<: mod$K, vars: {dropout: $dropout}}
  mod1:
    layers:
    - tf.keras.layers.Dense(2, activation="elu")
    - tf.keras.layers.Dense(125, activation="elu")
    - tf.keras.layers.Dropout(dropout)
    - tf.keras.layers.Dense(1, activation="sigmoid")
  mod2:
    layers:
    - tf.keras.layers.Dense(2, activation="elu")
    - tf.keras.layers.Dense(20, activation="elu")
    - tf.keras.layers.Dropout(dropout)
    - tf.keras.layers.Dense(20, activation="elu")
    - tf.keras.layers.Dropout(dropout)
    - tf.keras.layers.Dense(1, activation="sigmoid")
  mod3:
    layers:
    - tf.keras.layers.Dense(2, activation="elu")
    - tf.keras.layers.Dense(16, activation="elu")
    - tf.keras.layers.Dropout(dropout)
    - tf.keras.layers.Dense(16, activation="elu")
    - tf.keras.layers.Dropout(dropout)
    - tf.keras.layers.Dense(10, activation="elu")
    - tf.keras.layers.Dropout(dropout)
    - tf.keras.layers.Dense(1, activation="sigmoid")
  mod4:
    layers:
    - tf.keras.layers.Dense(2, activation="elu")
    - tf.keras.layers.Dense(11, activation="elu")
    - tf.keras.layers.Dropout(dropout)
    - tf.keras.layers.Dense(12, activation="elu")
    - tf.keras.layers.Dropout(dropout)
    - tf.keras.layers.Dense(12, activation="elu")
    - tf.keras.layers.Dropout(dropout)
    - tf.keras.layers.Dense(12, activation="elu")
    - tf.keras.layers.Dropout(dropout)
    - tf.keras.layers.Dense(1, activation="sigmoid")
  mod5:
    layers:
    - tf.keras.layers.Dense(2, activation="elu")
    - tf.keras.layers.Dense(11, activation="elu")
    - tf.keras.layers.Dropout(dropout)
    - tf.keras.layers.Dense(10, activation="elu")
    - tf.keras.layers.Dropout(dropout)
    - tf.keras.layers.Dense(10, activation="elu")
    - tf.keras.layers.Dropout(dropout)
    - tf.keras.layers.Dense(10, activation="elu")
    - tf.keras.layers.Dropout(dropout)
    - tf.keras.layers.Dense(10, activation="elu")
    - tf.keras.layers.Dropout(dropout)
    - tf.keras.layers.Dense(1, activation="sigmoid")
  common:
    samples: 100
    input:
      N: 4000
      train_frac: 0.8
      rescale: 50
      offset: 0
    compile:
      optimizer: adam
      loss: binary_crossentropy
      metrics: [accuracy]
      steps_per_execution: 4
    fit:
      epochs: 500
      batch_size: 50
      verbose: 0
50d3e336a6b911ec8a80fa163efacce8:
  <<<: common
  model: {<<<: mod1, vars: {dropout: 0.0}}
50f7088ea6b911ecabbffa163efacce8:
  <<<: common
  model: {<<<: mod1, vars: {dropout: 0.1}}
50f61186a6b911ec94ecfa163efacce8:
  <<<: common
  model: {<<<: mod1, vars: {dropout: 0.2}}
5111c5dea6b911ec9f8ffa163efacce8:
  <<<: common
  model: {<<<: mod1, vars: {dropout: 0.3}}
51304e28a6b911ecbd45fa163efacce8:
  <<<: common
  model: {<<<: mod2, vars: {dropout: 0.0}}
50f7087aa6b911ec8876fa163efacce8:
  <<<: common
  model: {<<<: mod2, vars: {dropout: 0.1}}
511616dea6b911ecb399fa163efacce8:
  <<<: common
  model: {<<<: mod2, vars: {dropout: 0.2}}
50f8b2baa6b911ec9b00fa163efacce8:
  <<<: common
  model: {<<<: mod2, vars: {dropout: 0.3}}
50d98278a6b911ec8959fa163efacce8:
  <<<: common
  model: {<<<: mod3, vars: {dropout: 0.0}}
50f7eec0a6b911ec821afa163efacce8:
  <<<: common
  model: {<<<: mod3, vars: {dropout: 0.1}}
50f72f30a6b911ec97a3fa163efacce8:
  <<<: common
  model: {<<<: mod3, vars: {dropout: 0.2}}
510f82eca6b911ec9deffa163efacce8:
  <<<: common
  model: {<<<: mod3, vars: {dropout: 0.3}}
51162336a6b911eca521fa163efacce8:
  <<<: common
  model: {<<<: mod4, vars: {dropout: 0.0}}
50daa6a8a6b911ec8ecefa163efacce8:
  <<<: common
  model: {<<<: mod4, vars: {dropout: 0.1}}
51304e1ea6b911ec9509fa163efacce8:
  <<<: common
  model: {<<<: mod4, vars: {dropout: 0.2}}
50fd502ca6b911ecb8fcfa163efacce8:
  <<<: common
  model: {<<<: mod4, vars: {dropout: 0.3}}
50f4f706a6b911ec90bffa163efacce8:
  <<<: common
  model: {<<<: mod5, vars: {dropout: 0.0}}
50fc0294a6b911ec84e0fa163efacce8:
  <<<: common
  model: {<<<: mod5, vars: {dropout: 0.1}}
50fe90eaa6b911ec82b3fa163efacce8:
  <<<: common
  model: {<<<: mod5, vars: {dropout: 0.2}}
50f8d3daa6b911ec89adfa163efacce8:
  <<<: common
  model: {<<<: mod5, vars: {dropout: 0.3}}










































