# from simsio import gen_configs
# import numpy as np
# params = {
#     "rescale": np.arange(2, 7) * 10,
#     "lr": np.logspace(-4, -1, 4),
# }
# gen_configs("template", params, "II/3A")
===:
  template: |
    n$enum:
      <<<: common
      input: {rescale: $rescale}
      compile: {optimizer: {config: {learning_rate: $lr}}}
  common:
    samples: 100
    input:
      N: 4000
      train_frac: 0.8
      offset: 0
    model:
      layers:
      - tf.keras.layers.Dense(2, activation="elu")
      - tf.keras.layers.Dense(20, activation="elu")
      - tf.keras.layers.Dense(20, activation="elu")
      - tf.keras.layers.Dropout(0.2)
      - tf.keras.layers.Dense(1, activation="sigmoid")
    compile:
      loss: binary_crossentropy
      optimizer:
        class_name: adam
      metrics: [accuracy]
      steps_per_execution: 4
    fit:
      epochs: 500
      batch_size: 50
      verbose: 0
n0:
  <<<: common
  input: {rescale: 20}
  compile: {optimizer: {config: {learning_rate: 0.0001}}}
n1:
  <<<: common
  input: {rescale: 20}
  compile: {optimizer: {config: {learning_rate: 0.001}}}
n2:
  <<<: common
  input: {rescale: 20}
  compile: {optimizer: {config: {learning_rate: 0.01}}}
n3:
  <<<: common
  input: {rescale: 20}
  compile: {optimizer: {config: {learning_rate: 0.1}}}
n4:
  <<<: common
  input: {rescale: 30}
  compile: {optimizer: {config: {learning_rate: 0.0001}}}
n5:
  <<<: common
  input: {rescale: 30}
  compile: {optimizer: {config: {learning_rate: 0.001}}}
n6:
  <<<: common
  input: {rescale: 30}
  compile: {optimizer: {config: {learning_rate: 0.01}}}
n7:
  <<<: common
  input: {rescale: 30}
  compile: {optimizer: {config: {learning_rate: 0.1}}}
n8:
  <<<: common
  input: {rescale: 40}
  compile: {optimizer: {config: {learning_rate: 0.0001}}}
n9:
  <<<: common
  input: {rescale: 40}
  compile: {optimizer: {config: {learning_rate: 0.001}}}
n10:
  <<<: common
  input: {rescale: 40}
  compile: {optimizer: {config: {learning_rate: 0.01}}}
n11:
  <<<: common
  input: {rescale: 40}
  compile: {optimizer: {config: {learning_rate: 0.1}}}
n12:
  <<<: common
  input: {rescale: 50}
  compile: {optimizer: {config: {learning_rate: 0.0001}}}
n13:
  <<<: common
  input: {rescale: 50}
  compile: {optimizer: {config: {learning_rate: 0.001}}}
n14:
  <<<: common
  input: {rescale: 50}
  compile: {optimizer: {config: {learning_rate: 0.01}}}
n15:
  <<<: common
  input: {rescale: 50}
  compile: {optimizer: {config: {learning_rate: 0.1}}}
n16:
  <<<: common
  input: {rescale: 60}
  compile: {optimizer: {config: {learning_rate: 0.0001}}}
n17:
  <<<: common
  input: {rescale: 60}
  compile: {optimizer: {config: {learning_rate: 0.001}}}
n18:
  <<<: common
  input: {rescale: 60}
  compile: {optimizer: {config: {learning_rate: 0.01}}}
n19:
  <<<: common
  input: {rescale: 60}
  compile: {optimizer: {config: {learning_rate: 0.1}}}
