name: ml
channels:
  - conda-forge
  - defaults
dependencies:
  - black
  - cxx-compiler
  - jupyter
  - hickle
  - keras
  - libblas[build=*mkl]
  - matplotlib>=3.5
  - nbconvert
  - numpy>=1.21
  - pip
  - pre-commit
  - python=3.9
  - scikit-learn
  - scipy>=1.7
  - setuptools>=42
  - tensorflow
  - pip:
    - -e simsio[keras]
    - -e mplotter[pdf]