# from simsio import gen_configs
# import numpy as np
# params = {
#     "N": 1000 * 2 ** np.arange(5),
#     "train_frac": np.arange(6, 10) / 10,
# }
# gen_configs("template", params, "II/1A")
===:
  template: |
    n$enum:
      <<<: common
      input: {N: $N, train_frac: $train_frac}
  common:
    samples: 100
    input:
      rescale: 50
      offset: 0
    model:
      layers:
      - tf.keras.layers.Dense(2, activation="relu")
      - tf.keras.layers.Dense(20, activation="relu")
      - tf.keras.layers.Dense(20, activation="relu")
      - tf.keras.layers.Dropout(0.2)
      - tf.keras.layers.Dense(1, activation="sigmoid")
    compile:
      loss: binary_crossentropy
      optimizer: adam
      metrics: [accuracy]
      steps_per_execution: 4
    fit:
      epochs: 500
      batch_size: 50
      verbose: 0
85511c10a65911ec85b2fa163efacce8:
  <<<: common
  input: {N: 1000, train_frac: 0.6}
85c5ca2ea65911ec95a3fa163e209104:
  <<<: common
  input: {N: 1000, train_frac: 0.7}
8551177ea65911ec99d2fa163efacce8:
  <<<: common
  input: {N: 1000, train_frac: 0.8}
85b788e2a65911ecb833fa163e66c7df:
  <<<: common
  input: {N: 1000, train_frac: 0.9}
85c98010a65911ecb447fa163e04b9dc:
  <<<: common
  input: {N: 2000, train_frac: 0.6}
85c5dbe0a65911ecb90afa163e209104:
  <<<: common
  input: {N: 2000, train_frac: 0.7}
85c98588a65911eca5bffa163e04b9dc:
  <<<: common
  input: {N: 2000, train_frac: 0.8}
85b77bf4a65911ec973afa163e66c7df:
  <<<: common
  input: {N: 2000, train_frac: 0.9}
855114fea65911ec90fbfa163efacce8:
  <<<: common
  input: {N: 4000, train_frac: 0.6}
85bcececa65911ecbdf5fa163e66c7df:
  <<<: common
  input: {N: 4000, train_frac: 0.7}
8558080ea65911ec9850fa163e595e79:
  <<<: common
  input: {N: 4000, train_frac: 0.8}
85c5c704a65911ecae77fa163e209104:
  <<<: common
  input: {N: 4000, train_frac: 0.9}
8557b11aa65911ecaa7cfa163e595e79:
  <<<: common
  input: {N: 8000, train_frac: 0.6}
8d2b6fdaa65911eca83afa163e209104:
  <<<: common
  input: {N: 8000, train_frac: 0.7}
85b78d24a65911eca2cffa163e66c7df:
  <<<: common
  input: {N: 8000, train_frac: 0.8}
855115c6a65911ec81a6fa163efacce8:
  <<<: common
  input: {N: 8000, train_frac: 0.9}
85514f96a65911eca646fa163efacce8:
  <<<: common
  input: {N: 16000, train_frac: 0.6}
85c97ad4a65911ec8926fa163e04b9dc:
  <<<: common
  input: {N: 16000, train_frac: 0.7}
855114fea65911eca9d8fa163efacce8:
  <<<: common
  input: {N: 16000, train_frac: 0.8}
85511bf2a65911ecbdf0fa163efacce8:
  <<<: common
  input: {N: 16000, train_frac: 0.9}










































