# from simsio import gen_configs
# import numpy as np
# params = {
#     "N": 1000 * 2 ** np.arange(5),
#     "train_frac": [0.6, 0.7, 0.8, 0.9],
#     "augment_frac": [0.0, 0.5, 1.0],
#     "augment_std": [0.05, 0.10],
# }
# gen_configs("template", params, "1")
===:
  template: |
    n$enum:
      <<<: common
      input: {N: $N, train_frac: $train_frac, augment_frac: $augment_frac, augment_std: $augment_std}
  common:
    samples: 50
    input:
      box: 100
    model:
      name: model
      layers:
      - tf.keras.layers.Dense(2, activation="relu")
      - tf.keras.layers.Dense(20, activation="relu")
      - tf.keras.layers.Dense(20, activation="relu")
      - tf.keras.layers.Dropout(0.2)
      - tf.keras.layers.Dense(1, activation="sigmoid")
    compile:
      loss: binary_crossentropy
      optimizer: adam
      metrics: [accuracy]
      steps_per_execution: 4
    fit:
      epochs: 500
      batch_size: 50
      verbose: 0
87e605c0a18711ecaf65fa163efacce8:
  <<<: common
  input: {N: 1000, train_frac: 0.6, augment_frac: 0.0, augment_std: 0.05}
431acc76a19811ecbf6ffa163e209104:
  <<<: common
  input: {N: 1000, train_frac: 0.6, augment_frac: 0.0, augment_std: 0.1}
b7e35264a1a511ec8210fa163e04b9dc:
  <<<: common
  input: {N: 1000, train_frac: 0.6, augment_frac: 0.5, augment_std: 0.05}
062aa5aea19611ecae37fa163e04b9dc:
  <<<: common
  input: {N: 1000, train_frac: 0.6, augment_frac: 0.5, augment_std: 0.1}
34e6115ca1b011ec9848fa163e66c7df:
  <<<: common
  input: {N: 1000, train_frac: 0.6, augment_frac: 1.0, augment_std: 0.05}
a3105954a18711ecaa13fa163e04b9dc:
  <<<: common
  input: {N: 1000, train_frac: 0.6, augment_frac: 1.0, augment_std: 0.1}
4729d0bea1b111ec96c4fa163e04b9dc:
  <<<: common
  input: {N: 1000, train_frac: 0.7, augment_frac: 0.0, augment_std: 0.05}
8913a128a18711ec8dc2fa163e04b9dc:
  <<<: common
  input: {N: 1000, train_frac: 0.7, augment_frac: 0.0, augment_std: 0.1}
47bc908ea19d11eca348fa163e66c7df:
  <<<: common
  input: {N: 1000, train_frac: 0.7, augment_frac: 0.5, augment_std: 0.05}
ded0e070a19c11ec8a27fa163efacce8:
  <<<: common
  input: {N: 1000, train_frac: 0.7, augment_frac: 0.5, augment_std: 0.1}
c3c08094a1ae11ec957dfa163ea6f025:
  <<<: common
  input: {N: 1000, train_frac: 0.7, augment_frac: 1.0, augment_std: 0.05}
9cf8a474a1a811eca2a9fa163e66c7df:
  <<<: common
  input: {N: 1000, train_frac: 0.7, augment_frac: 1.0, augment_std: 0.1}
8b87c70ea18711ec8e64fa163ea6f025:
  <<<: common
  input: {N: 1000, train_frac: 0.8, augment_frac: 0.0, augment_std: 0.05}
885a3a16a19c11ec82ecfa163efacce8:
  <<<: common
  input: {N: 1000, train_frac: 0.8, augment_frac: 0.0, augment_std: 0.1}
87e5c092a18711ec9953fa163efacce8:
  <<<: common
  input: {N: 1000, train_frac: 0.8, augment_frac: 0.5, augment_std: 0.05}
87e5ca10a18711ec8b68fa163efacce8:
  <<<: common
  input: {N: 1000, train_frac: 0.8, augment_frac: 0.5, augment_std: 0.1}
8804e760a18711ec8926fa163e595e79:
  <<<: common
  input: {N: 1000, train_frac: 0.8, augment_frac: 1.0, augment_std: 0.05}
3f1e5044a1a611eca50ffa163efacce8:
  <<<: common
  input: {N: 1000, train_frac: 0.8, augment_frac: 1.0, augment_std: 0.1}
98c2d836a1a111ecadf8fa163e66c7df:
  <<<: common
  input: {N: 1000, train_frac: 0.9, augment_frac: 0.0, augment_std: 0.05}
5e7ac5e8a19311ec96dafa163efacce8:
  <<<: common
  input: {N: 1000, train_frac: 0.9, augment_frac: 0.0, augment_std: 0.1}
1b5f4deea1a011ec8187fa163e66c7df:
  <<<: common
  input: {N: 1000, train_frac: 0.9, augment_frac: 0.5, augment_std: 0.05}
87e5f292a18711eca7eafa163efacce8:
  <<<: common
  input: {N: 1000, train_frac: 0.9, augment_frac: 0.5, augment_std: 0.1}
6057d5b0a1a511ecb1f7fa163ea6f025:
  <<<: common
  input: {N: 1000, train_frac: 0.9, augment_frac: 1.0, augment_std: 0.05}
1f7aed46a19811ec9555fa163ea6f025:
  <<<: common
  input: {N: 1000, train_frac: 0.9, augment_frac: 1.0, augment_std: 0.1}
86c5d652a1af11ecb0dafa163efacce8:
  <<<: common
  input: {N: 2000, train_frac: 0.6, augment_frac: 0.0, augment_std: 0.05}
646a173ea19711ec93b9fa163e209104:
  <<<: common
  input: {N: 2000, train_frac: 0.6, augment_frac: 0.0, augment_std: 0.1}
8913b88ea18711ec8860fa163e04b9dc:
  <<<: common
  input: {N: 2000, train_frac: 0.6, augment_frac: 0.5, augment_std: 0.05}
1c023d82a1a611ec9665fa163efacce8:
  <<<: common
  input: {N: 2000, train_frac: 0.6, augment_frac: 0.5, augment_std: 0.1}
a3429c34a18711ec89a3fa163e595e79:
  <<<: common
  input: {N: 2000, train_frac: 0.6, augment_frac: 1.0, augment_std: 0.05}
a4ea4abea18711ecaf8afa163e209104:
  <<<: common
  input: {N: 2000, train_frac: 0.6, augment_frac: 1.0, augment_std: 0.1}
895917a8a18711ec93e6fa163e66c7df:
  <<<: common
  input: {N: 2000, train_frac: 0.7, augment_frac: 0.0, augment_std: 0.05}
dadb7c54a1a211ecb4e2fa163e04b9dc:
  <<<: common
  input: {N: 2000, train_frac: 0.7, augment_frac: 0.0, augment_std: 0.1}
71d18408a19611ecabc9fa163e595e79:
  <<<: common
  input: {N: 2000, train_frac: 0.7, augment_frac: 0.5, augment_std: 0.05}
f7488dcea1a111ec8d72fa163e595e79:
  <<<: common
  input: {N: 2000, train_frac: 0.7, augment_frac: 0.5, augment_std: 0.1}
8b87cc22a18711ecb932fa163ea6f025:
  <<<: common
  input: {N: 2000, train_frac: 0.7, augment_frac: 1.0, augment_std: 0.05}
c24880e2a1a211eca457fa163efacce8:
  <<<: common
  input: {N: 2000, train_frac: 0.7, augment_frac: 1.0, augment_std: 0.1}
8b87bf20a18711ecbc60fa163ea6f025:
  <<<: common
  input: {N: 2000, train_frac: 0.8, augment_frac: 0.0, augment_std: 0.05}
ea3e118ca19511ec84f4fa163e04b9dc:
  <<<: common
  input: {N: 2000, train_frac: 0.8, augment_frac: 0.0, augment_std: 0.1}
ac348ef6a18711ecbd39fa163e209104:
  <<<: common
  input: {N: 2000, train_frac: 0.8, augment_frac: 0.5, augment_std: 0.05}
6b76606aa19611ec89e4fa163e04b9dc:
  <<<: common
  input: {N: 2000, train_frac: 0.8, augment_frac: 0.5, augment_std: 0.1}
80a068c2a19711ecb101fa163e66c7df:
  <<<: common
  input: {N: 2000, train_frac: 0.8, augment_frac: 1.0, augment_std: 0.05}
88050bc8a18711ec8bb5fa163e595e79:
  <<<: common
  input: {N: 2000, train_frac: 0.8, augment_frac: 1.0, augment_std: 0.1}
8913a984a18711ec8d80fa163e04b9dc:
  <<<: common
  input: {N: 2000, train_frac: 0.9, augment_frac: 0.0, augment_std: 0.05}
7fed3f82a19611ecac84fa163efacce8:
  <<<: common
  input: {N: 2000, train_frac: 0.9, augment_frac: 0.0, augment_std: 0.1}
8805153ca18711ecad8bfa163e595e79:
  <<<: common
  input: {N: 2000, train_frac: 0.9, augment_frac: 0.5, augment_std: 0.05}
8b87bed0a18711eca207fa163ea6f025:
  <<<: common
  input: {N: 2000, train_frac: 0.9, augment_frac: 0.5, augment_std: 0.1}
8a2f8a72a18711ecbad3fa163efacce8:
  <<<: common
  input: {N: 2000, train_frac: 0.9, augment_frac: 1.0, augment_std: 0.05}
88fed70ca18711ec9e59fa163e209104:
  <<<: common
  input: {N: 2000, train_frac: 0.9, augment_frac: 1.0, augment_std: 0.1}
88fe7e1aa18711ecb0ecfa163e209104:
  <<<: common
  input: {N: 4000, train_frac: 0.6, augment_frac: 0.0, augment_std: 0.05}
88051136a18711ecbd3ffa163e595e79:
  <<<: common
  input: {N: 4000, train_frac: 0.6, augment_frac: 0.0, augment_std: 0.1}
89590830a18711ecb6a8fa163e66c7df:
  <<<: common
  input: {N: 4000, train_frac: 0.6, augment_frac: 0.5, augment_std: 0.05}
47fede44a19811ec8482fa163efacce8:
  <<<: common
  input: {N: 4000, train_frac: 0.6, augment_frac: 0.5, augment_std: 0.1}
8b87bd54a18711ec9e15fa163ea6f025:
  <<<: common
  input: {N: 4000, train_frac: 0.6, augment_frac: 1.0, augment_std: 0.05}
aafb8606a19711eca235fa163ea6f025:
  <<<: common
  input: {N: 4000, train_frac: 0.6, augment_frac: 1.0, augment_std: 0.1}
31e983f8a1a611ecb565fa163ea6f025:
  <<<: common
  input: {N: 4000, train_frac: 0.7, augment_frac: 0.0, augment_std: 0.05}
cced1b18a18711ecb7a6fa163e209104:
  <<<: common
  input: {N: 4000, train_frac: 0.7, augment_frac: 0.0, augment_std: 0.1}
96388de4a1a211eca675fa163e66c7df:
  <<<: common
  input: {N: 4000, train_frac: 0.7, augment_frac: 0.5, augment_std: 0.05}
88fe8cfca18711ec88ecfa163e209104:
  <<<: common
  input: {N: 4000, train_frac: 0.7, augment_frac: 0.5, augment_std: 0.1}
8958fda4a18711ec9be0fa163e66c7df:
  <<<: common
  input: {N: 4000, train_frac: 0.7, augment_frac: 1.0, augment_std: 0.05}
63502944a1a911ec865afa163e66c7df:
  <<<: common
  input: {N: 4000, train_frac: 0.7, augment_frac: 1.0, augment_std: 0.1}
586b28c8a1b111ec93adfa163e66c7df:
  <<<: common
  input: {N: 4000, train_frac: 0.8, augment_frac: 0.0, augment_std: 0.05}
6eb40350a19f11ecb940fa163e04b9dc:
  <<<: common
  input: {N: 4000, train_frac: 0.8, augment_frac: 0.0, augment_std: 0.1}
74fd6576a1ae11ec8fe4fa163ea6f025:
  <<<: common
  input: {N: 4000, train_frac: 0.8, augment_frac: 0.5, augment_std: 0.05}
a3b9b7e2a18711ecbb86fa163e04b9dc:
  <<<: common
  input: {N: 4000, train_frac: 0.8, augment_frac: 0.5, augment_std: 0.1}
88053c9ca18711ec96c7fa163e595e79:
  <<<: common
  input: {N: 4000, train_frac: 0.8, augment_frac: 1.0, augment_std: 0.05}
7dc4f6c2a19c11ec9a6bfa163ea6f025:
  <<<: common
  input: {N: 4000, train_frac: 0.8, augment_frac: 1.0, augment_std: 0.1}
7a13f502a1a411ec8471fa163e209104:
  <<<: common
  input: {N: 4000, train_frac: 0.9, augment_frac: 0.0, augment_std: 0.05}
a26b3424a19b11ec9572fa163e04b9dc:
  <<<: common
  input: {N: 4000, train_frac: 0.9, augment_frac: 0.0, augment_std: 0.1}
796c6ebea1a311eca42dfa163e595e79:
  <<<: common
  input: {N: 4000, train_frac: 0.9, augment_frac: 0.5, augment_std: 0.05}
87e5da82a18711ecb8e9fa163efacce8:
  <<<: common
  input: {N: 4000, train_frac: 0.9, augment_frac: 0.5, augment_std: 0.1}
6a89e690a19611ec9ef0fa163e595e79:
  <<<: common
  input: {N: 4000, train_frac: 0.9, augment_frac: 1.0, augment_std: 0.05}
8958e774a18711eca6fdfa163e66c7df:
  <<<: common
  input: {N: 4000, train_frac: 0.9, augment_frac: 1.0, augment_std: 0.1}
07d0d3c8a1a111ecba54fa163efacce8:
  <<<: common
  input: {N: 8000, train_frac: 0.6, augment_frac: 0.0, augment_std: 0.05}
9ce1bc08a18711ecbdc9fa163e04b9dc:
  <<<: common
  input: {N: 8000, train_frac: 0.6, augment_frac: 0.0, augment_std: 0.1}
87e5bc3ca18711eca759fa163efacce8:
  <<<: common
  input: {N: 8000, train_frac: 0.6, augment_frac: 0.5, augment_std: 0.05}
57bfcdc8a19511ec9f9dfa163e595e79:
  <<<: common
  input: {N: 8000, train_frac: 0.6, augment_frac: 0.5, augment_std: 0.1}
e3d77812a1a211ecbec0fa163e66c7df:
  <<<: common
  input: {N: 8000, train_frac: 0.6, augment_frac: 1.0, augment_std: 0.05}
09b01560a1af11ec89f6fa163e66c7df:
  <<<: common
  input: {N: 8000, train_frac: 0.6, augment_frac: 1.0, augment_std: 0.1}
8b87e194a18711ec9eddfa163ea6f025:
  <<<: common
  input: {N: 8000, train_frac: 0.7, augment_frac: 0.0, augment_std: 0.05}
e0a7b138a1ad11eca24dfa163e595e79:
  <<<: common
  input: {N: 8000, train_frac: 0.7, augment_frac: 0.0, augment_std: 0.1}
8b87c2aea18711ec84cdfa163ea6f025:
  <<<: common
  input: {N: 8000, train_frac: 0.7, augment_frac: 0.5, augment_std: 0.05}
41545d18a1b011ec8bdbfa163e595e79:
  <<<: common
  input: {N: 8000, train_frac: 0.7, augment_frac: 0.5, augment_std: 0.1}
0da6f940a19b11ec8acefa163e595e79:
  <<<: common
  input: {N: 8000, train_frac: 0.7, augment_frac: 1.0, augment_std: 0.05}
8805bfdca18711eca8defa163e595e79:
  <<<: common
  input: {N: 8000, train_frac: 0.7, augment_frac: 1.0, augment_std: 0.1}
8b87f238a18711ecbd95fa163ea6f025:
  <<<: common
  input: {N: 8000, train_frac: 0.8, augment_frac: 0.0, augment_std: 0.05}
5b84cbd4a19511ecba0cfa163ea6f025:
  <<<: common
  input: {N: 8000, train_frac: 0.8, augment_frac: 0.0, augment_std: 0.1}
172c17c8a19811ecb51afa163e209104:
  <<<: common
  input: {N: 8000, train_frac: 0.8, augment_frac: 0.5, augment_std: 0.05}
12a4faf6a19a11ec8504fa163e209104:
  <<<: common
  input: {N: 8000, train_frac: 0.8, augment_frac: 0.5, augment_std: 0.1}
db967f36a1ac11ec8240fa163e209104:
  <<<: common
  input: {N: 8000, train_frac: 0.8, augment_frac: 1.0, augment_std: 0.05}
786b2a2ca19f11ecacb1fa163ea6f025:
  <<<: common
  input: {N: 8000, train_frac: 0.8, augment_frac: 1.0, augment_std: 0.1}
89591636a18711ec8f6efa163e66c7df:
  <<<: common
  input: {N: 8000, train_frac: 0.9, augment_frac: 0.0, augment_std: 0.05}
89592482a18711ec98a3fa163e66c7df:
  <<<: common
  input: {N: 8000, train_frac: 0.9, augment_frac: 0.0, augment_std: 0.1}
6840c098a19611ec9a77fa163ea6f025:
  <<<: common
  input: {N: 8000, train_frac: 0.9, augment_frac: 0.5, augment_std: 0.05}
1f127720a19811ec9373fa163e209104:
  <<<: common
  input: {N: 8000, train_frac: 0.9, augment_frac: 0.5, augment_std: 0.1}
87e5dbf4a18711ecb743fa163efacce8:
  <<<: common
  input: {N: 8000, train_frac: 0.9, augment_frac: 1.0, augment_std: 0.05}
7ed417d0a19411ecb0eefa163efacce8:
  <<<: common
  input: {N: 8000, train_frac: 0.9, augment_frac: 1.0, augment_std: 0.1}
a374e630a18711ec807afa163e04b9dc:
  <<<: common
  input: {N: 16000, train_frac: 0.6, augment_frac: 0.0, augment_std: 0.05}
88fe80c2a18711ec8524fa163e209104:
  <<<: common
  input: {N: 16000, train_frac: 0.6, augment_frac: 0.0, augment_std: 0.1}
9455895ca19611eca033fa163e04b9dc:
  <<<: common
  input: {N: 16000, train_frac: 0.6, augment_frac: 0.5, augment_std: 0.05}
eefa85f8a1ad11ec9c72fa163e04b9dc:
  <<<: common
  input: {N: 16000, train_frac: 0.6, augment_frac: 0.5, augment_std: 0.1}
92c6c74ea1b011eca3b8fa163e04b9dc:
  <<<: common
  input: {N: 16000, train_frac: 0.6, augment_frac: 1.0, augment_std: 0.05}
88fe7e42a18711ec9c60fa163e209104:
  <<<: common
  input: {N: 16000, train_frac: 0.6, augment_frac: 1.0, augment_std: 0.1}
eb0d8c8ca19f11ec9358fa163ea6f025:
  <<<: common
  input: {N: 16000, train_frac: 0.7, augment_frac: 0.0, augment_std: 0.05}
ad5496cea1ae11eca12dfa163e04b9dc:
  <<<: common
  input: {N: 16000, train_frac: 0.7, augment_frac: 0.0, augment_std: 0.1}
1cc0bb72a19711ec88b3fa163e209104:
  <<<: common
  input: {N: 16000, train_frac: 0.7, augment_frac: 0.5, augment_std: 0.05}
81d585d4a1a511ecaa18fa163efacce8:
  <<<: common
  input: {N: 16000, train_frac: 0.7, augment_frac: 0.5, augment_std: 0.1}
172d76eca1aa11ec9bbefa163e595e79:
  <<<: common
  input: {N: 16000, train_frac: 0.7, augment_frac: 1.0, augment_std: 0.05}
f6a8728ca1a411ecb5ddfa163e209104:
  <<<: common
  input: {N: 16000, train_frac: 0.7, augment_frac: 1.0, augment_std: 0.1}
f86b7e7aa19511ecb6e4fa163e595e79:
  <<<: common
  input: {N: 16000, train_frac: 0.8, augment_frac: 0.0, augment_std: 0.05}
89590e98a18711ec84fdfa163e66c7df:
  <<<: common
  input: {N: 16000, train_frac: 0.8, augment_frac: 0.0, augment_std: 0.1}
89590cc2a18711ec8bc0fa163e66c7df:
  <<<: common
  input: {N: 16000, train_frac: 0.8, augment_frac: 0.5, augment_std: 0.05}
8913babea18711ecb279fa163e04b9dc:
  <<<: common
  input: {N: 16000, train_frac: 0.8, augment_frac: 0.5, augment_std: 0.1}
94523d58a1a311eca3f0fa163e04b9dc:
  <<<: common
  input: {N: 16000, train_frac: 0.8, augment_frac: 1.0, augment_std: 0.05}
7ed6ca98a19411ecaeaefa163efacce8:
  <<<: common
  input: {N: 16000, train_frac: 0.8, augment_frac: 1.0, augment_std: 0.1}
71204c88a19611ec9397fa163e595e79:
  <<<: common
  input: {N: 16000, train_frac: 0.9, augment_frac: 0.0, augment_std: 0.05}
1925e642a1ae11ecafeffa163e595e79:
  <<<: common
  input: {N: 16000, train_frac: 0.9, augment_frac: 0.0, augment_std: 0.1}
f7294b54a1af11ecb8aafa163efacce8:
  <<<: common
  input: {N: 16000, train_frac: 0.9, augment_frac: 0.5, augment_std: 0.05}
9d167722a18711ec8b4cfa163e595e79:
  <<<: common
  input: {N: 16000, train_frac: 0.9, augment_frac: 0.5, augment_std: 0.1}
7ed79a7ca19411ecbf26fa163efacce8:
  <<<: common
  input: {N: 16000, train_frac: 0.9, augment_frac: 1.0, augment_std: 0.05}
9bb8e080a1b011ecbd4bfa163efacce8:
  <<<: common
  input: {N: 16000, train_frac: 0.9, augment_frac: 1.0, augment_std: 0.1}



















































































































































































































































