# from simsio import gen_configs
# params = {
#     "activation": [
#         "elu",
#         "relu",
#         "sigmoid",
#         "softsign",
#         "tanh",
#     ],
#     "optimizer": [
#         "adam",
#         "adamax",
#         "rmsprop",
#         "sgd",
#         "{name: sgd, nesterov: True}",
#     ],
# }
# gen_configs("template", params, "2A")
===:
  template: |
    n$enum:
      <<<: common
      compile: {optimizer: $optimizer}
      model: {activation: $activation}
  common:
    samples: 100
    input:
      N: 8000
      box: 100
      train_frac: 0.8
      augment_frac: 0.0
      augment_std: 0.0
    model:
      name: model
      layers:
      - tf.keras.layers.Dense(2, activation=activation)
      - tf.keras.layers.Dense(20, activation=activation)
      - tf.keras.layers.Dense(20, activation=activation)
      - tf.keras.layers.Dropout(0.2)
      - tf.keras.layers.Dense(1, activation="sigmoid")
    compile:
      loss: binary_crossentropy
      metrics: [accuracy]
      steps_per_execution: 4
    fit:
      epochs: 500
      batch_size: 50
      verbose: 0
n0:
  <<<: common
  compile: {optimizer: adam}
  model: {activation: elu}
n1:
  <<<: common
  compile: {optimizer: adamax}
  model: {activation: elu}
n2:
  <<<: common
  compile: {optimizer: rmsprop}
  model: {activation: elu}
n3:
  <<<: common
  compile: {optimizer: sgd}
  model: {activation: elu}
n4:
  <<<: common
  compile: {optimizer: {name: sgd, nesterov: true}}
  model: {activation: elu}
n5:
  <<<: common
  compile: {optimizer: adam}
  model: {activation: relu}
n6:
  <<<: common
  compile: {optimizer: adamax}
  model: {activation: relu}
n7:
  <<<: common
  compile: {optimizer: rmsprop}
  model: {activation: relu}
n8:
  <<<: common
  compile: {optimizer: sgd}
  model: {activation: relu}
n9:
  <<<: common
  compile: {optimizer: {name: sgd, nesterov: true}}
  model: {activation: relu}
n10:
  <<<: common
  compile: {optimizer: adam}
  model: {activation: sigmoid}
n11:
  <<<: common
  compile: {optimizer: adamax}
  model: {activation: sigmoid}
n12:
  <<<: common
  compile: {optimizer: rmsprop}
  model: {activation: sigmoid}
n13:
  <<<: common
  compile: {optimizer: sgd}
  model: {activation: sigmoid}
n14:
  <<<: common
  compile: {optimizer: {name: sgd, nesterov: true}}
  model: {activation: sigmoid}
n15:
  <<<: common
  compile: {optimizer: adam}
  model: {activation: softsign}
n16:
  <<<: common
  compile: {optimizer: adamax}
  model: {activation: softsign}
n17:
  <<<: common
  compile: {optimizer: rmsprop}
  model: {activation: softsign}
n18:
  <<<: common
  compile: {optimizer: sgd}
  model: {activation: softsign}
n19:
  <<<: common
  compile: {optimizer: {name: sgd, nesterov: true}}
  model: {activation: softsign}
n20:
  <<<: common
  compile: {optimizer: adam}
  model: {activation: tanh}
n21:
  <<<: common
  compile: {optimizer: adamax}
  model: {activation: tanh}
n22:
  <<<: common
  compile: {optimizer: rmsprop}
  model: {activation: tanh}
n23:
  <<<: common
  compile: {optimizer: sgd}
  model: {activation: tanh}
n24:
  <<<: common
  compile: {optimizer: {name: sgd, nesterov: true}}
  model: {activation: tanh}


