# from simsio import gen_configs
# params = {
#     "activation": [
#         "elu",
#         "relu",
#         "sigmoid",
#         "softsign",
#         "tanh",
#     ],
#     "optimizer": [
#         "adam",
#         "adamax",
#         "rmsprop",
#         "sgd",
#         "{name: sgd, nesterov: True}",
#     ],
# }
# gen_configs("template", params, "2A")
===:
  template: |
    n$enum:
      <<<: common
      compile: {optimizer: $optimizer}
      model: {activation: $activation}
  common:
    samples: 100
    input:
      N: 8000
      box: 100
      train_frac: 0.8
      augment_frac: 0.0
      augment_std: 0.0
    model:
      name: model
      layers:
      - tf.keras.layers.Dense(2, activation=activation)
      - tf.keras.layers.Dense(20, activation=activation)
      - tf.keras.layers.Dense(20, activation=activation)
      - tf.keras.layers.Dropout(0.2)
      - tf.keras.layers.Dense(1, activation="sigmoid")
    compile:
      loss: binary_crossentropy
      metrics: [accuracy]
      steps_per_execution: 4
    fit:
      epochs: 500
      batch_size: 50
      verbose: 0
56b0f3baa3bd11ecb4aefa163ea6f025:
  <<<: common
  compile: {optimizer: adam}
  model: {activation: elu}
5524f294a3bd11ec85f9fa163e595e79:
  <<<: common
  compile: {optimizer: adamax}
  model: {activation: elu}
57d7546ea3bd11eca6b5fa163efacce8:
  <<<: common
  compile: {optimizer: rmsprop}
  model: {activation: elu}
57efd26ea3bd11ecbfd5fa163efacce8:
  <<<: common
  compile: {optimizer: sgd}
  model: {activation: elu}
63141e2aa3bd11ec9221fa163ea6f025-R:
  <<<: common
  compile: {optimizer: {name: sgd, nesterov: true}}
  model: {activation: elu}
55d60390a3bd11ecb5a4fa163e66c7df:
  <<<: common
  compile: {optimizer: adam}
  model: {activation: relu}
664a56aea3bd11ecbc41fa163ea6f025:
  <<<: common
  compile: {optimizer: adamax}
  model: {activation: relu}
5af75d2ea3bd11ecafeafa163e209104:
  <<<: common
  compile: {optimizer: rmsprop}
  model: {activation: relu}
55af8026a3bd11ecade7fa163e209104:
  <<<: common
  compile: {optimizer: sgd}
  model: {activation: relu}
55d5e202a3bd11ecb87ffa163e66c7df-R:
  <<<: common
  compile: {optimizer: {name: sgd, nesterov: true}}
  model: {activation: relu}
5ce55b36a3bd11ec8924fa163efacce8:
  <<<: common
  compile: {optimizer: adam}
  model: {activation: sigmoid}
55af96cea3bd11ecab31fa163e209104:
  <<<: common
  compile: {optimizer: adamax}
  model: {activation: sigmoid}
5524f1e0a3bd11eca686fa163e595e79:
  <<<: common
  compile: {optimizer: rmsprop}
  model: {activation: sigmoid}
55af8fc6a3bd11ec838afa163e209104:
  <<<: common
  compile: {optimizer: sgd}
  model: {activation: sigmoid}
55d5f5f8a3bd11ec84a7fa163e66c7df-R:
  <<<: common
  compile: {optimizer: {name: sgd, nesterov: true}}
  model: {activation: sigmoid}
55d5e220a3bd11ec816afa163e66c7df:
  <<<: common
  compile: {optimizer: adam}
  model: {activation: softsign}
63b4edb4a3bd11ec8a95fa163e04b9dc:
  <<<: common
  compile: {optimizer: adamax}
  model: {activation: softsign}
5de6fe0ea3bd11ecaa86fa163e595e79:
  <<<: common
  compile: {optimizer: rmsprop}
  model: {activation: softsign}
55e42f7ea3bd11ecaea4fa163e04b9dc:
  <<<: common
  compile: {optimizer: sgd}
  model: {activation: softsign}
5de2bfeca3bd11ecb072fa163e66c7df-R:
  <<<: common
  compile: {optimizer: {name: sgd, nesterov: true}}
  model: {activation: softsign}
5524f49ca3bd11ec898efa163e595e79:
  <<<: common
  compile: {optimizer: adam}
  model: {activation: tanh}
5dacd1f2a3bd11ec9eb3fa163e66c7df:
  <<<: common
  compile: {optimizer: adamax}
  model: {activation: tanh}
553a3de8a3bd11ec86e3fa163efacce8:
  <<<: common
  compile: {optimizer: rmsprop}
  model: {activation: tanh}
5f17d0a0a3bd11eca9f4fa163e04b9dc:
  <<<: common
  compile: {optimizer: sgd}
  model: {activation: tanh}
553a3adca3bd11ec89c4fa163efacce8-R:
  <<<: common
  compile: {optimizer: {name: sgd, nesterov: true}}
  model: {activation: tanh}










































