# from simsio import gen_configs
# import numpy as np
# params = {
#     "N": 1000 * 2 ** np.arange(1, 5),
#     "M": np.arange(5, 26, 5),
# }
# gen_configs("template", params, "II/2B")
===:
  template: |
    n$enum:
      <<<: common
      input: {N: $N}
      model: {vars: {M: $M}}
  common:
    samples: 100
    input:
      train_frac: 0.8
      rescale: 50
      offset: 0
    model:
      layers:
      - tf.keras.layers.Dense(2, activation="elu")
      - tf.keras.layers.Dense(M, activation="elu")
      - tf.keras.layers.Dense(M, activation="elu")
      - tf.keras.layers.Dropout(0.2)
      - tf.keras.layers.Dense(1, activation="sigmoid")
    compile:
      optimizer: adam
      loss: binary_crossentropy
      metrics: [accuracy]
      steps_per_execution: 4
    fit:
      epochs: 500
      batch_size: 50
      verbose: 0
9452530ea68c11ec802afa163e04b9dc:
  <<<: common
  input: {N: 2000}
  model: {vars: {M: 5}}
02465aeea6a211ecaf28fa163ee812fb:
  <<<: common
  input: {N: 2000}
  model: {vars: {M: 10}}
025162c2a6a211ec9f6bfa163ee812fb:
  <<<: common
  input: {N: 2000}
  model: {vars: {M: 15}}
030b5970a6a211ec97a6fa163ee812fb:
  <<<: common
  input: {N: 2000}
  model: {vars: {M: 20}}
941f1688a68c11ecacc2fa163e04b9dc:
  <<<: common
  input: {N: 2000}
  model: {vars: {M: 25}}
01de4260a6a211ec8856fa163ee812fb:
  <<<: common
  input: {N: 4000}
  model: {vars: {M: 5}}
941c6b9aa68c11ec9c93fa163e04b9dc:
  <<<: common
  input: {N: 4000}
  model: {vars: {M: 10}}
941c70a4a68c11eca03afa163e04b9dc:
  <<<: common
  input: {N: 4000}
  model: {vars: {M: 15}}
01de4058a6a211ecb92ffa163ee812fb:
  <<<: common
  input: {N: 4000}
  model: {vars: {M: 20}}
02516600a6a211ecb61cfa163ee812fb:
  <<<: common
  input: {N: 4000}
  model: {vars: {M: 25}}
941c0f7ea68c11eca734fa163e04b9dc:
  <<<: common
  input: {N: 8000}
  model: {vars: {M: 5}}
025a1796a6a211eca992fa163ee812fb:
  <<<: common
  input: {N: 8000}
  model: {vars: {M: 10}}
020b8978a6a211ecab2cfa163ee812fb:
  <<<: common
  input: {N: 8000}
  model: {vars: {M: 15}}
02414608a6a211ec83b7fa163ee812fb:
  <<<: common
  input: {N: 8000}
  model: {vars: {M: 20}}
030a73c0a6a211ecb5cafa163ee812fb:
  <<<: common
  input: {N: 8000}
  model: {vars: {M: 25}}
941c71d0a68c11ec8fcafa163e04b9dc:
  <<<: common
  input: {N: 16000}
  model: {vars: {M: 5}}
0215cf3ca6a211ecbeeafa163ee812fb:
  <<<: common
  input: {N: 16000}
  model: {vars: {M: 10}}
9450c0fca68c11ec9888fa163e04b9dc:
  <<<: common
  input: {N: 16000}
  model: {vars: {M: 15}}
025162c2a6a211ec876efa163ee812fb:
  <<<: common
  input: {N: 16000}
  model: {vars: {M: 20}}
940e3782a68c11ec9b16fa163e04b9dc:
  <<<: common
  input: {N: 16000}
  model: {vars: {M: 25}}










































